#include "shared/recording/codec.hpp"
#include "shared/protocol/frame.hpp"
#include <cstring>
namespace rail {
static void put16(std::ostream&o,uint16_t v){o.put(char(v));o.put(char(v>>8));}static void put32(std::ostream&o,uint32_t v){for(int i=0;i<4;i++)o.put(char(v>>(8*i)));}static void put64(std::ostream&o,uint64_t v){for(int i=0;i<8;i++)o.put(char(v>>(8*i)));}
static uint16_t g16(const uint8_t*p){return uint16_t(p[0]|(uint16_t(p[1])<<8));}static uint32_t g32(const uint8_t*p){uint32_t v=0;for(int i=0;i<4;i++)v|=uint32_t(p[i])<<(8*i);return v;}static uint64_t g64(const uint8_t*p){uint64_t v=0;for(int i=0;i<8;i++)v|=uint64_t(p[i])<<(8*i);return v;}
Status write_record(std::ostream&o,const Record&r){if(r.payload.size()>16*1024*1024||r.device_id.size()>255)return Status::failure(ErrorCode::InvalidArgument,"record too large");Bytes body;body.reserve(64+r.payload.size()+r.device_id.size());auto a=[&](uint8_t x){body.push_back(x);};auto b16=[&](uint16_t x){a(uint8_t(x));a(uint8_t(x>>8));};auto b32=[&](uint32_t x){for(int i=0;i<4;i++)a(uint8_t(x>>(8*i)));};auto b64=[&](uint64_t x){for(int i=0;i<8;i++)a(uint8_t(x>>(8*i)));};b16(r.type);b16(r.stream);a(uint8_t(r.device_id.size()));body.insert(body.end(),r.device_id.begin(),r.device_id.end());b64(r.time.ticks);b32(r.time.ticks_per_second);b32(r.time.boot_id);a(uint8_t(r.time.quality));a(uint8_t(r.time.domain));b64(r.sequence);b64(r.host_monotonic_ns);a(uint8_t(r.simulated));b32(uint32_t(r.payload.size()));body.insert(body.end(),r.payload.begin(),r.payload.end());if(body.size()>0xffffffffu)return Status::failure(ErrorCode::Overflow,"record length");o.write("RIRE",4);put32(o,uint32_t(body.size()));o.write(reinterpret_cast<const char*>(body.data()),std::streamsize(body.size()));put32(o,crc32(body.data(),body.size()));return o.good()?Status::success():Status::failure(ErrorCode::IoError,"write failed");}
Status read_record(const uint8_t*p,size_t n,Record&r,size_t&used){used=0;if(n<12||std::memcmp(p,"RIRE",4)!=0)return Status::failure(ErrorCode::CorruptData,"bad record header");uint32_t len=g32(p+4);if(len>16*1024*1024||n<12+len)return Status::failure(ErrorCode::CorruptData,"truncated record");if(crc32(p+8,len)!=g32(p+8+len))return Status::failure(ErrorCode::CorruptData,"bad record crc");size_t i=8;const size_t end=8+len;r.type=g16(p+i);i+=2;r.stream=g16(p+i);i+=2;uint8_t dl=p[i++];if(i+dl>end)return Status::failure(ErrorCode::CorruptData,"bad device");r.device_id.assign(reinterpret_cast<const char*>(p+i),dl);i+=dl;r.time.ticks=g64(p+i);i+=8;r.time.ticks_per_second=g32(p+i);i+=4;r.time.boot_id=g32(p+i);i+=4;r.time.quality=TimeQuality(p[i++]);if(i>=end)return Status::failure(ErrorCode::CorruptData,"missing clock domain");r.time.domain=ClockDomain(p[i++]);r.sequence=g64(p+i);i+=8;r.host_monotonic_ns=g64(p+i);i+=8;r.simulated=p[i++]!=0;uint32_t pl=g32(p+i);i+=4;if(i+pl!=end)return Status::failure(ErrorCode::CorruptData,"bad payload length");r.payload.assign(p+i,p+i+pl);used=12+len;return Status::success();}
}
